# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c2f5a51876729f9fca5996181729441f2a86a2bec4c220bdaa0f957ae300d287ce734fa53179aee34b6b4744552ab951b9d12f0461de490c55695327118bd14

test:
  secret_key_base: 4edd3d3df301e88a07a3637f509ab77025a6b6c5aef887c5ad4fbed5cc961205d8dbc601b82a87afa310b078a7d8094abcc51b9071a7c867411dfec51bee923b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
